services:
  mongodb:
    image: mongo:5.0.6
    ports:
      - 27017:27017
    volumes:
      - type: volume
        source: mongo-database
        target: /data/db


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/


  accounts_management:
    image: accounts_management:latest
    # expose on port 9000 so it doesn't conflict with the debug servers we might run during development
    ports:
      - 9000:8000
    environment:
      MONGO_CONNECT_STR: "mongodb://mongodb:27017/accounts"


# specify the database directories as volumes, to avoid performance overhead of bind mounts
# https://docs.docker.com/storage/volumes/
# https://github.com/docker/for-mac/issues/4981#issuecomment-733796401
# https://engageinteractive.co.uk/blog/making-docker-faster-on-mac
volumes:
  mongo-database: