services:
  mongodb:
    image: mongo:5.0.6
    ports:
      - 27017:27017
    # environment:
    #      MONGO_INITDB_ROOT_USERNAME: root
    #      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - type: volume
        source: mongo-database
        target: /data/db


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
      #      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      #      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      #      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017/

# specify the database directories as volumes, to avoid performance overhead of bind mounts
# https://docs.docker.com/storage/volumes/
# https://github.com/docker/for-mac/issues/4981#issuecomment-733796401
# https://engageinteractive.co.uk/blog/making-docker-faster-on-mac
volumes:
  mongo-database: